// Generated by CoffeeScript 1.8.0
(function() {
  var Interval, WeightSet, convertToTimedInterval, timeFormatter;

  WeightSet = require('../../weightSet');

  Interval = require('../../interval');

  timeFormatter = require('../../timeFormatter');

  convertToTimedInterval = function(currentSet, time, distance) {
    currentSet.intervals.pop();
    return currentSet.intervals.push(new Interval({
      time: time,
      distance: distance
    }));
  };

  module.exports = {
    canHandle: function(token, currentSet) {
      return token === '-' && currentSet instanceof WeightSet;
    },
    act: function(tokens, token, currentSet) {
      if (tokens.length === 5) {
        currentSet.current().weight = parseFloat(tokens[0]);
        currentSet.current().reps = parseInt(tokens[3], 10);
      }
      if (tokens.length === 4) {
        convertToTimedInterval(currentSet, timeFormatter.toDuration(tokens[3]), parseFloat(tokens[0]));
      }
      if (tokens.length === 2) {
        currentSet.current().reps = parseInt(tokens[0], 10);
      }
      if (tokens.length === 1) {
        convertToTimedInterval(currentSet, timeFormatter.toDuration(tokens[0]));
      }
      return tokens.length = 0;
    }
  };

}).call(this);
