// Generated by CoffeeScript 1.8.0
(function() {
  var Workout;

  Workout = require('../../workout');

  module.exports = {
    canHandle: function(token) {
      return token === '**';
    },
    act: function(tokens, token, currentSet, workout) {
      var name;
      tokens.unshift(token);
      name = tokens.join(' ');
      tokens.length = 0;
      workout.sets.pop();
      return currentSet = workout.addSet(name);
    }
  };

}).call(this);
