// Generated by CoffeeScript 1.8.0
(function() {
  var WeightSet;

  WeightSet = require('../../weightSet');

  module.exports = {
    canHandle: function(token, currentSet) {
      return token === '-' && currentSet instanceof WeightSet;
    },
    act: function(tokens, token, currentSet) {
      if (tokens.length === 5) {
        currentSet.current().weight = parseFloat(tokens[0]);
        currentSet.current().reps = parseInt(tokens[3], 10);
      }
      if (tokens.length === 2) {
        currentSet.current().reps = parseInt(tokens[0], 10);
      }
      return tokens.length = 0;
    }
  };

}).call(this);
