// Generated by CoffeeScript 1.8.0
(function() {
  var Weight;

  module.exports = Weight = (function() {
    function Weight(options) {
      if (options) {
        this.reps = options.reps, this.weight = options.weight;
      }
      if (this.reps == null) {
        this.reps = 0;
      }
      if (this.weight == null) {
        this.weight = 0;
      }
    }

    Weight.prototype.isEmpty = function() {
      return this.reps === 0 && this.weight === 0;
    };

    Weight.prototype.toJSON = function() {
      return {
        reps: this.reps,
        weight: this.weight
      };
    };

    Weight.prototype.toString = function() {
      if (this.weight) {
        return "- " + this.weight + " lbs x " + this.reps + " reps";
      } else {
        return "- " + this.reps + " reps";
      }
    };

    return Weight;

  })();

}).call(this);
